#!/usr/bin/env python3
"""Generate a weekly changelog of all upstream skill repositories.

Scans EVERY upstream in upstream-manifest.yaml (including disabled ones),
pulls latest changes, and reports commits from the last N days grouped by repo.
"""

import argparse
import subprocess
import sys
import tempfile
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
MANIFEST_PATH = PROJECT_ROOT / "migration" / "upstream-manifest.yaml"
REPORT_DIR = Path.home() / ".agents" / "work-reports" / "upstream-changelog"


def parse_manifest():
    """Extract all upstream repos from manifest, regardless of disabled state."""
    import yaml
    manifest = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))
    repos = []
    for u in manifest.get("upstreams", []):
        info = {
            "id": u["id"],
            "label": u.get("label", u["id"]),
            "repo": u.get("repo", ""),
            "branch": u.get("branch", "main"),
        }
        if info["repo"]:
            repos.append(info)
    return repos


def git_log_since(repo_dir, branch, since_date):
    """Get commits since date for a bare clone. Returns list of commit lines."""
    try:
        subprocess.run(
            ["git", "fetch", "origin", f"{branch}:refs/heads/{branch}"],
            cwd=repo_dir, capture_output=True, timeout=30, check=False
        )
        result = subprocess.run(
            ["git", "log", f"--since={since_date}", "--oneline", "--no-merges",
             f"refs/heads/{branch}"],
            cwd=repo_dir, capture_output=True, text=True, timeout=15, check=False
        )
        if result.returncode != 0:
            return [], f"git log failed: {result.stderr[:200]}"
        lines = result.stdout.strip().split("\n")
        commits = [l for l in lines if l.strip()]
        return commits, None
    except Exception as e:
        return [], str(e)


def clone_or_pull(repo_url, branch, cache_dir):
    """Ensure a cached clone exists; return its path."""
    import hashlib
    key = hashlib.md5(f"{repo_url}:{branch}".encode()).hexdigest()[:10]
    repo_dir = cache_dir / f"{key}"
    if (repo_dir / ".git").is_dir():
        subprocess.run(["git", "fetch", "origin", branch],
                       cwd=repo_dir, capture_output=True, timeout=60, check=False)
    else:
        subprocess.run(["git", "clone", "--bare", "--filter=blob:none",
                        "--single-branch", "--branch", branch,
                        repo_url, str(repo_dir)],
                       capture_output=True, timeout=120, check=False)
    return repo_dir


def generate_report(repos, since_date, cache_dir):
    """Generate Markdown report grouped by upstream."""
    lines = [
        f"# Upstream Skill Changelog",
        f"",
        f"> {since_date.strftime('%Y-%m-%d')} — {datetime.now().strftime('%Y-%m-%d')}",
        f"> {len(repos)} upstreams checked",
        f"",
    ]

    for r in repos:
        print(f"  Checking {r['id']} ({r['repo']})...", file=sys.stderr)
        repo_dir = clone_or_pull(r["repo"], r["branch"], cache_dir)
        commits, error = git_log_since(repo_dir, r["branch"], since_date.strftime("%Y-%m-%d"))

        lines.append(f"## {r['label']}")
        lines.append(f"*{r['repo']}#{r['branch']}*")
        lines.append("")

        if error:
            lines.append(f"⚠️ {error}")
        elif not commits:
            lines.append("*No new commits this week.*")
        else:
            for c in commits[:30]:  # cap at 30 per repo
                lines.append(f"- `{c}`")

        lines.append("")

    # Summary footer
    total = sum(1 for r in repos if True)  # placeholder for later
    lines.append("---")
    lines.append(f"*Generated by upstream-changelog · {datetime.now().isoformat()}*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", help="Start date (YYYY-MM-DD), default: 7 days ago")
    parser.add_argument("--output", help="Output file, default: auto-generated path")
    parser.add_argument("--cache-dir", help="Repo cache directory",
                        default=str(Path.home() / ".cache" / "upstream-changelog"))
    args = parser.parse_args()

    since = datetime.strptime(args.since, "%Y-%m-%d") if args.since else datetime.now() - timedelta(days=7)

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    output = Path(args.output) if args.output else REPORT_DIR / f"{since.strftime('%Y-%m-%d')}.md"

    cache_dir = Path(args.cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)

    repos = parse_manifest()
    print(f"Scanning {len(repos)} upstreams (since {since.strftime('%Y-%m-%d')})...", file=sys.stderr)

    report = generate_report(repos, since, cache_dir)
    output.write_text(report, encoding="utf-8")

    print(f"\nSaved: {output}", file=sys.stderr)


if __name__ == "__main__":
    main()
